---
- name: Install and configure Kafka with KRaft
  hosts: "{{ kafka_target_hosts }}"
  become: true
  vars:
    kraft_roles: "{{ 'controller,broker' if kafka_node_role == 'controller_broker' else 'broker' }}"
  roles:
    - firewall
    - kafka
