---
- name: Include pre-installation tasks
  include_tasks: pre_install.yml
  tags: pre-install

- name: Include installation tasks
  include_tasks: install.yml
  tags: kafka-install

- name: Include configuration tasks
  include_tasks: configure.yml
  when: kafka_configure | bool
  tags: kafka-configure

- name: Include services setup tasks
  include_tasks: service.yml
  when: kafka_setup_service | bool
  tags: kafka-services
