---
- name: restart redis
  systemd:
    name: redis
    state: restarted
    enabled: yes
    daemon_reload: yes

- name: Reload and Restart Redis
  block:
    - name: Reload systemd
      command: systemctl daemon-reexec
      become: true
    - name: Reload daemon and restart redis
      systemd:
        name: redis
        state: restarted
        daemon_reload: true
      become: true
